import os
import sys
import re
from psycopg import connect
from dotenv import load_dotenv
import litellm

# Load env variables explicitly
load_dotenv(dotenv_path=os.path.join(os.getcwd(), ".env"))

# Configure LiteLLM to use GEMINI_API_KEY from environment
# (LiteLLM automatically picks up GEMINI_API_KEY when calling gemini/ models)
GEMINI_API_KEY = os.getenv("GEMINI_API_KEY")
if not GEMINI_API_KEY:
    print("Warning: GEMINI_API_KEY is not set in your .env file.")

# Static database schema definition provided to the baseline prompt
DB_SCHEMA_PROMPT = """
You are a PostgreSQL expert. Translate the user's natural language question into a valid PostgreSQL SQL query.
Return ONLY the raw SQL query. Do not wrap it in markdown block formatting like ```sql ... ``` and do not provide any explanations.

Here are the database tables and columns:

1. Table: customers
   - customer_id (integer, PRIMARY KEY)
   - name (varchar)
   - email (varchar, UNIQUE)
   - signup_date (date)
   - country (varchar)

2. Table: products
   - product_id (integer, PRIMARY KEY)
   - name (varchar)
   - category (varchar)
   - price (decimal)

3. Table: orders
   - order_id (integer, PRIMARY KEY)
   - customer_id (integer, FOREIGN KEY references customers.customer_id)
   - order_date (date)
   - total_amount (decimal)
   - status (varchar: 'Pending', 'Completed', 'Cancelled')

4. Table: order_items
   - order_item_id (integer, PRIMARY KEY)
   - order_id (integer, FOREIGN KEY references orders.order_id)
   - product_id (integer, FOREIGN KEY references products.product_id)
   - quantity (integer)
   - unit_price (decimal)

5. Table: payments
   - payment_id (integer, PRIMARY KEY)
   - order_id (integer, FOREIGN KEY references orders.order_id)
   - payment_date (date)
   - amount (decimal)
   - payment_status (varchar: 'Pending', 'Completed', 'Failed', 'Refunded')
"""

def clean_sql(sql_text: str) -> str:
    """Cleans up the SQL generated by the LLM by removing code block markdown formatting."""
    # Remove markdown code blocks if the LLM ignored instructions
    sql_text = re.sub(r"```sql\s*", "", sql_text, flags=re.IGNORECASE)
    sql_text = re.sub(r"```\s*", "", sql_text)
    return sql_text.strip()

def execute_query(sql_query: str):
    """Executes the SQL query against the querypilot database and returns the result."""
    conn = None
    try:
        conn = connect(
            host=os.getenv("DB_HOST", "localhost"),
            port=os.getenv("DB_PORT", "5432"),
            user=os.getenv("DB_USER", "postgres"),
            password=os.getenv("DB_PASSWORD"),
            dbname=os.getenv("DB_NAME", "querypilot")
        )
        with conn.cursor() as cur:
            cur.execute(sql_query)
            # Check if query returned rows (e.g. SELECT)
            if cur.description:
                colnames = [desc[0] for desc in cur.description]
                rows = cur.fetchall()
                return colnames, rows
            else:
                conn.commit()
                return None, "Command executed successfully (No results returned)."
    except Exception as e:
        return None, f"Database Error: {e}"
    finally:
        if conn:
            conn.close()

def main():
    print("==================================================")
    print("        TEXT-TO-SQL BASELINE PIPELINE             ")
    print("==================================================")
    print("Type 'exit' to quit.\n")

    # We will use gemini/gemini-3.5-flash as our baseline model
    model_name = "gemini/gemini-3.5-flash"

    while True:
        try:
            question = input("\nYou: ").strip()
            if not question:
                continue
            if question.lower() in ["exit", "quit"]:
                print("Exiting baseline baseline pipeline. Goodbye!")
                break

            print("\nGenerating SQL...")
            
            # Formulate the prompt
            prompt = f"{DB_SCHEMA_PROMPT}\nUser Question: {question}\nSQL Query:"
            
            # Call LiteLLM
            response = litellm.completion(
                model=model_name,
                messages=[{"role": "user", "content": prompt}],
                temperature=0.0
            )
            
            generated_sql = response.choices[0].message.content
            cleaned_sql = clean_sql(generated_sql)
            
            print(f"\nGenerated SQL:\n{cleaned_sql}")
            print("\nExecuting query against PostgreSQL...")
            
            columns, results = execute_query(cleaned_sql)
            
            if columns:
                # Print column headers
                header_line = " | ".join(columns)
                print("-" * len(header_line))
                print(header_line)
                print("-" * len(header_line))
                # Print rows
                for row in results:
                    print(" | ".join(str(val) for val in row))
                print("-" * len(header_line))
            else:
                print(results)
                
        except KeyboardInterrupt:
            print("\nExiting baseline pipeline. Goodbye!")
            break
        except Exception as e:
            print(f"\nAn error occurred: {e}")

if __name__ == "__main__":
    main()
